---
title: "General Table of Contents"
output:
  html_document:
    theme: united
---
# Papers

1. Introduction
2. Methods
3. Results
4. Discussion


1. Introduction
2. Literature Review
3. Data
4. Methodology
5. Results
6. Conclusion


1. Introduction
2. Theorethical Framework
3. Econometric Models and Estimation Methods
4. Data
5. Results
6. Conclusion

# Research Proposal

Your research proposal should provide details on:

your main research question
the relevant literature and your planned contribution to the current research in the area
the econometric and/or theoretical modelling methods that you plan to use
the data source (only if you envisage empirical work).
The proposal should be of about 1,000 to 2,000 words.

# Abstracts

- Background
- Purpose
- Methods (What did you do?)
- Results (What did you find?)
- Conclusions (What does it mean?)

# Introductions

Why did you start?

- Significance
- Status Quo; Background Information; Literature Review; "What we know"
- Create a Gap; Rationale; "What we don't know"
- Fill the Gap; Aim of the Study

## Research Problem

- Background of the problem
- Problem statement
- Significance of the problem

# Methods

How did you do?

# Results

What did you find?

# Discussion

What does it all mean?

# References

[Tips and Tools for Writing](http://writingcenter.unc.edu/tips-and-tools/argument/)

[THOMPSON WRITING PROGRAM](http://twp.duke.edu/)

[TU Delft MSc Geomatics](https://tudelftgeomatics.github.io/thesis/)

[Global Communication Center](https://www.cmu.edu/gcc/HandoutsandResources/index.html)

[Novelty Handout](https://www.cmu.edu/gcc/handouts/Novelty%20Handout.pdf)

[Preparing Structured Abstracts](http://sites.ieee.org/pcs/transactions-of-professional-communication/for-prospective-authors/guidelines-to-follow/preparing-structured-abstracts/)

[Phrasebank](http://www.phrasebank.manchester.ac.uk/)

[The Introduction Formula](http://blogs.ubc.ca/khead/research/research-advice/formula)

[THE CONCLUSION FORMULA](http://marcfbellemare.com/wordpress/12060)

[HOW TO PUBLISH IN ACADEMIC JOURNALS](http://marcfbellemare.com/wordpress/12501)